using System.Collections;
using System.Collections.Generic;
using UnityEngine;


namespace MapPieces
{
	public static class TestPieces
	{
		static public List<Piece> allTestPiecesPieces;
		//---------------------------------------------------------------------------
		//---------- Piece Declerations ---------------------------------------------
		//---------------------------------------------------------------------------
		public static Piece TestRoomPiece;
		public static Piece TestRoomPiece2;
		public static Piece TestRoomPiece2walls;
		public static Piece TestRoomPiece2walls_f;
		public static Piece TestRoomPiece2walls_f_F;
		public static Piece TestRoomPiece2_F;
		public static Piece TestRoomPiece3Walls;
		public static Piece TestRoomPiece3Walls_f;
		public static Piece TestRoomPiece3Walls_f_F;
		public static Piece TestRoomPieceCorner;
		public static Piece TestRoomPieceCorner_f;
		public static Piece TestRoomPieceCorner_ff;
		public static Piece TestRoomPieceCorner_fff;
		public static Piece TestRoomPieceCorner_fff_F;
		public static Piece TestRoomPieceCorner_ff_F;
		public static Piece TestRoomPieceCorner_f_F;
		public static Piece TestRoomPieceDoor;
		public static Piece TestRoomPieceDoor_F;
		public static Piece TestRoomPiecePit;
		public static Piece TestRoomPiecePit_F;
		public static Piece TestRoomPieceWall;
		public static Piece TestRoomPieceWall_f;
		public static Piece TestRoomPieceWall_ff;
		public static Piece TestRoomPieceWall_fff;
		public static Piece TestRoomPieceWall_fff_F;
		public static Piece TestRoomPieceWall_ff_F;
		public static Piece TestRoomPieceWall_f_F;
		public static Piece TestRoomPiece_F;
		public static Piece Test_Inactive_Piece;
		public static Piece Test_Inactive_Piece_F;
		static TestPieces()
		{
			TestRoomPiece = new Piece("TestRoomPiece", "../Resources/RoomPieces//TestPieces/TestRoomPiece_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPieceWall_fff_F}},
				{"E", new List<Piece>(){}},
				{"SE", new List<Piece>(){TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPieceWall_fff}},
				{"W", new List<Piece>(){}},
				{"NW", new List<Piece>(){TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPiece2 = new Piece("TestRoomPiece2", "../Resources/RoomPieces//TestPieces/TestRoomPiece2_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPieceWall_fff}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPieceWall_fff_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPiece2walls = new Piece("TestRoomPiece2walls", "../Resources/RoomPieces//TestPieces/TestRoomPiece2walls_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPiece2walls_f = new Piece("TestRoomPiece2walls_f", "../Resources/RoomPieces//TestPieces/TestRoomPiece2walls_f_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPiece2walls_f_F = new Piece("TestRoomPiece2walls_f_F", "../Resources/RoomPieces//TestPieces/TestRoomPiece2walls_f_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPiece2_F = new Piece("TestRoomPiece2_F", "../Resources/RoomPieces//TestPieces/TestRoomPiece2_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPieceWall_fff}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPieceWall_fff_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPiece3Walls = new Piece("TestRoomPiece3Walls", "../Resources/RoomPieces//TestPieces/TestRoomPiece3Walls_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPiece3Walls_f = new Piece("TestRoomPiece3Walls_f", "../Resources/RoomPieces//TestPieces/TestRoomPiece3Walls_f_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPiece3Walls_f_F = new Piece("TestRoomPiece3Walls_f_F", "../Resources/RoomPieces//TestPieces/TestRoomPiece3Walls_f_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceCorner = new Piece("TestRoomPieceCorner", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceCorner_f = new Piece("TestRoomPieceCorner_f", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_f_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceWall_fff}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceCorner_ff = new Piece("TestRoomPieceCorner_ff", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_ff_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPieceCorner_fff = new Piece("TestRoomPieceCorner_fff", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_fff_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceWall_fff_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceCorner_fff_F = new Piece("TestRoomPieceCorner_fff_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_fff_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPieceCorner_ff_F = new Piece("TestRoomPieceCorner_ff_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_ff_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceWall_fff_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceCorner_f_F = new Piece("TestRoomPieceCorner_f_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceCorner_f_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceDoor = new Piece("TestRoomPieceDoor", "../Resources/RoomPieces//TestPieces/TestRoomPieceDoor_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceWall_fff}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceDoor_F = new Piece("TestRoomPieceDoor_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceDoor_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceWall_fff}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPiecePit = new Piece("TestRoomPiecePit", "../Resources/RoomPieces//TestPieces/TestRoomPiecePit_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceWall_fff_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall_fff}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPiecePit_F = new Piece("TestRoomPiecePit_F", "../Resources/RoomPieces//TestPieces/TestRoomPiecePit_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPieceWall_fff}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPieceWall_fff_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPieceWall = new Piece("TestRoomPieceWall", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_fff}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceWall_f = new Piece("TestRoomPieceWall_f", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_f_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_fff}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPieceWall_ff = new Piece("TestRoomPieceWall_ff", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_ff_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_fff_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPieceWall_fff = new Piece("TestRoomPieceWall_fff", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_fff_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, TestRoomPiece_F}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F}},
				{"NW", new List<Piece>(){}}};
			TestRoomPieceWall_fff_F = new Piece("TestRoomPieceWall_fff_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_fff_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPieceWall_fff}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPieceWall_fff}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f}},
				{"W", new List<Piece>(){TestRoomPieceWall_ff_F, TestRoomPiece_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPiece_F}}};
			TestRoomPieceWall_ff_F = new Piece("TestRoomPieceWall_ff_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_ff_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPiece_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_ff}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_ff}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPiece_F}}};
			TestRoomPieceWall_f_F = new Piece("TestRoomPieceWall_f_F", "../Resources/RoomPieces//TestPieces/TestRoomPieceWall_f_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, Test_Inactive_Piece, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPiece_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPiece_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, Test_Inactive_Piece, Test_Inactive_Piece_F}}};
			TestRoomPiece_F = new Piece("TestRoomPiece_F", "../Resources/RoomPieces//TestPieces/TestRoomPiece_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F}},
				{"NE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPieceWall_f_F}},
				{"E", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_f, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F}},
				{"SE", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F}},
				{"S", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F}},
				{"SW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, TestRoomPieceWall_f_F}},
				{"W", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2_F, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F}},
				{"NW", new List<Piece>(){TestRoomPiece, TestRoomPiece2, TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece2_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPiecePit, TestRoomPiecePit_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F}}};
			Test_Inactive_Piece = new Piece("Test_Inactive_Piece", "../Resources/RoomPieces//TestPieces/Test_Inactive_Piece_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece_F}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece_F}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece_F}},
				{"SE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece_F}},
				{"S", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece_F}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece_F}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece_F}},
				{"NW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece_F}}};
			Test_Inactive_Piece_F = new Piece("Test_Inactive_Piece_F", "../Resources/RoomPieces//TestPieces/Test_Inactive_Piece_F_Prefab.prefab", new Dictionary<string, List<Piece>>(){ 
				{"N", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff, TestRoomPieceWall_f_F, Test_Inactive_Piece}},
				{"NE", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_fff, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_fff, Test_Inactive_Piece}},
				{"E", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceCorner_f_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff, TestRoomPieceWall_ff_F, Test_Inactive_Piece}},
				{"SE", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_ff_F, Test_Inactive_Piece}},
				{"S", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_ff_F, TestRoomPieceWall_ff, TestRoomPieceWall_fff_F, TestRoomPieceWall_ff_F, Test_Inactive_Piece}},
				{"SW", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls_f, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceWall_fff_F, Test_Inactive_Piece}},
				{"W", new List<Piece>(){TestRoomPiece2walls, TestRoomPiece2walls_f, TestRoomPiece2walls_f_F, TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_ff, TestRoomPieceCorner_fff_F, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_fff_F, TestRoomPieceWall_f_F, Test_Inactive_Piece}},
				{"NW", new List<Piece>(){TestRoomPiece3Walls, TestRoomPiece3Walls_f, TestRoomPiece3Walls_f_F, TestRoomPieceCorner, TestRoomPieceCorner_f, TestRoomPieceCorner_f_F, TestRoomPieceDoor, TestRoomPieceDoor_F, TestRoomPieceWall, TestRoomPieceWall_f, TestRoomPieceWall_f_F, Test_Inactive_Piece}}};
		}
	}

}